# Site settings
title: Getting Shit Done
email: website@gtez.org
description: Jesse Houston's personal website and blog
baseurl: "/gtez.github.io/"
url: "http://gtez.com"
domain: "gtez.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

